# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('content', models.TextField()),
                ('is_show', models.BooleanField(default=False, verbose_name='是否可见')),
            ],
            options={
                'db_table': 'artical',
            },
        ),
    ]
